### ISSUE TITLE
support for pangolin v3.0.1

### ISSUE THREAD

**Issue by SupriseCestEric** [jaleezyy/covid-19-signal#118]
Lineage assignment fails in our pipeline since updating to PANGOLIN v3.0.1

We get the following error message. 

Traceback (most recent call last):
  File "/home/usr/covid-19-signal/scripts/assign_lineages.py", line 154, in <module>
    pangolin = run_pangolin(args.input_genomes, args.threads)
  File "/home/usr/covid-19-signal/scripts/assign_lineages.py", line 76, in run_pangolin
    stderr=subprocess.DEVNULL)
  File "/home/usr/covid-19-signal/.snakemake/conda/1381b0a843d86b9bf650deb5d2536cb9/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/usr/covid-19-signal/.snakemake/conda/1381b0a843d86b9bf650deb5d2536cb9/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pangolin', 'all_genomes.fa', '-t', '2', '-o', 'pangolin_tmp_1622126844.257058']' returned non-zero exit status 1.

Thanks

**Comment by fmaguire** [comment]
Updating this right now!

**Comment by fmaguire** [comment]
Should all be fixed and updated now if you re-run the workflow.
